/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Abilities {
  description: string | null;
  energyCost: number | null;
  id: Generated<string>;
  name: string;
  needsReloading: boolean;
  oncePerGame: boolean | null;
  oncePerTurn: boolean | null;
  pulse: boolean | null;
  range: number | null;
  type: string;
}

export interface AbilityType {
  abilityType: string;
}

export interface ArcaneOutcomeCardColors {
  color: string;
}

export interface ArcaneOutcomeCards {
  arcaneOutcomeId: string;
  color: string | null;
  id: string;
  isCatastrophe: boolean;
  value: string | null;
}

export interface ArcaneOutcomeCardValues {
  value: string;
}

export interface ArcaneOutcomes {
  abilityId: string;
  id: Generated<string>;
  outcomeText: string;
}

export interface Characters {
  arcane: number | null;
  baseSize: string;
  energy: number[];
  evade: number;
  fullFilename: string | null;
  headFilename: string | null;
  health: number;
  id: Generated<string>;
  melee: number | null;
  meleeRange: number | null;
  name: string;
  signatureMoveId: string | null;
}

export interface CharactersToAbilities {
  abilityId: string;
  characterId: string;
}

export interface CharactersToFactions {
  characterId: string;
  faction: string;
}

export interface CharactersToKeywords {
  characterId: string;
  keyword: string;
}

export interface DamageTypes {
  damageType: string;
}

export interface Factions {
  faction: string;
}

export interface Keywords {
  keyword: string;
}

export interface MeleeMoves {
  additionalEffects: string | null;
  endStep: string | null;
  id: Generated<string>;
  name: string;
  upgradesId: string | null;
}

export interface MeleeMovesToDamageTypes {
  damageType: string;
  meleeMoveId: string;
}

export interface MeleeOutcomes {
  damage: number | null;
  isCounter: boolean;
  meleeMoveId: string;
  opposingMoveId: string;
}

export interface DB {
  abilities: Abilities;
  abilityType: AbilityType;
  arcaneOutcomeCardColors: ArcaneOutcomeCardColors;
  arcaneOutcomeCards: ArcaneOutcomeCards;
  arcaneOutcomeCardValues: ArcaneOutcomeCardValues;
  arcaneOutcomes: ArcaneOutcomes;
  characters: Characters;
  charactersToAbilities: CharactersToAbilities;
  charactersToFactions: CharactersToFactions;
  charactersToKeywords: CharactersToKeywords;
  damageTypes: DamageTypes;
  factions: Factions;
  keywords: Keywords;
  meleeMoves: MeleeMoves;
  meleeMovesToDamageTypes: MeleeMovesToDamageTypes;
  meleeOutcomes: MeleeOutcomes;
}
